/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class JNITYPE_p_f_p_struct_vtree_t_p_struct_sdd_manager_t__p_vtree_t extends JniPointer {

  protected JNITYPE_p_f_p_struct_vtree_t_p_struct_sdd_manager_t__p_vtree_t(long cPtr) {
    super(cPtr);
  }

}

