/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class JNITYPE_p_wmc_manager_t extends JniPointer {

  protected JNITYPE_p_wmc_manager_t(long cPtr) {
    super(cPtr);
  }
}

