/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public class JNITYPE_p_sdd_node_t extends JniPointer {

  public JNITYPE_p_sdd_node_t(long cPtr) {
	  super(cPtr);
  }
}

