/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package jni;

public interface SddLibConstants {
  public final static String PRIsS = SddLibJNI.PRIsS_get();
  public final static String PRInsS = SddLibJNI.PRInsS_get();
  public final static String PRIrcS = SddLibJNI.PRIrcS_get();
  public final static String PRImcS = SddLibJNI.PRImcS_get();
  public final static String PRIlitS = SddLibJNI.PRIlitS_get();
  public final static int CONJOIN = SddLibJNI.CONJOIN_get();
  public final static int DISJOIN = SddLibJNI.DISJOIN_get();
}
